---
version: 2
updates:
  - package-ecosystem: "gomod"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "vendor"
    labels:
      - vendor
