---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-csiaddons-openshift-io-v1alpha1-csiaddonsnode
  failurePolicy: Fail
  name: vcsiaddonsnode.kb.io
  rules:
  - apiGroups:
    - csiaddons.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - csiaddonsnodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-csiaddons-openshift-io-v1alpha1-networkfence
  failurePolicy: Fail
  name: vnetworkfence.kb.io
  rules:
  - apiGroups:
    - csiaddons.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - networkfences
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-csiaddons-openshift-io-v1alpha1-reclaimspacecronjob
  failurePolicy: Fail
  name: vreclaimspacecronjob.kb.io
  rules:
  - apiGroups:
    - csiaddons.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - reclaimspacecronjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-csiaddons-openshift-io-v1alpha1-reclaimspacejob
  failurePolicy: Fail
  name: vreclaimspacejob.kb.io
  rules:
  - apiGroups:
    - csiaddons.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - reclaimspacejobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-replication-storage-openshift-io-v1alpha1-volumereplication
  failurePolicy: Fail
  name: vvolumereplication.kb.io
  rules:
  - apiGroups:
    - replication.storage.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - volumereplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-replication-storage-openshift-io-v1alpha1-volumereplicationclass
  failurePolicy: Fail
  name: vvolumereplicationclass.kb.io
  rules:
  - apiGroups:
    - replication.storage.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - volumereplicationclasses
  sideEffects: None
