---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-addons-config
  # replace the namespace with the namespace where the operator is deployed.
  namespace: csi-addons-system
data:
  "reclaim-space-timeout": "3m"
  "max-concurrent-reconciles": "100"
  "max-group-pvcs": "100"
  "csi-addons-node-retry-delay": "5"
