---
# permissions for end users to view networkfences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfence-viewer-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfences/status
  verbs:
  - get
