---
# permissions for end users to edit networkfences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfence-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfences/status
  verbs:
  - get
