---
name: Publish container images in quay.io

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  push_bundle:
    name: Push bundle container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install gpgme for operator-sdk
        run: sudo apt-get update && sudo apt-get install -y libgpgme-dev

      - name: Generate the bundle contents
        run: make bundle

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push bundle container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          tags: quay.io/csiaddons/k8s-bundle:latest

  push_controller:
    name: Push controller container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push controller container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          tags: quay.io/csiaddons/k8s-controller:latest

  push_sidecar:
    name: Push sidecar container image to quay.io
    if: github.repository == 'csi-addons/kubernetes-csi-addons'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push sidecar container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Containerfile.sidecar
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          tags: quay.io/csiaddons/k8s-sidecar:latest
