---
name: Test building container images

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"

jobs:
  build_bundle:
    name: build_bundle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install gpgme for operator-sdk
        run: sudo apt-get update && sudo apt-get install -y libgpgme-dev

      - name: Generate the bundle contents
        run: make bundle

      - name: Validate the bundle contents
        run: make bundle-validate

      - name: Build bundle container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: bundle.Dockerfile
          push: false
          tags: quay.io/csiaddons/k8s-bundle:latest

  build_controller:
    name: build_controller
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: false
          tags: quay.io/csiaddons/k8s-controller:latest

  build_sidecar:
    name: build_sidecar
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build sidecar container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Containerfile.sidecar
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: false
          tags: quay.io/csiaddons/k8s-sidecar:latest
