---
name: Test building container images

on:
  pull_request:
    branches:
      - "*"

jobs:
  build_bundle:
    name: build_bundle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Generate the bundle contents
        run: make bundle

      - name: Validate the bundle contents
        run: make bundle-validate

      - name: Build bundle container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: bundle.Dockerfile
          push: false
          tags: quay.io/csiaddons/k8s-bundle:latest

  build_controller:
    name: build_controller
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: ${{ secrets.BUILD_PLATFORMS }}
          push: false
          tags: quay.io/csiaddons/k8s-controller:latest

  build_sidecar:
    name: build_sidecar
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build sidecar container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Containerfile.sidecar
          platforms: ${{ secrets.BUILD_PLATFORMS }}
          push: false
          tags: quay.io/csiaddons/k8s-sidecar:latest
